services:
  - type: web
    name: fastapi-ws-app   # kies zelf een naam
    env: docker            # omdat je een Dockerfile gebruikt
    plan: free
    buildCommand: ""       # Dockerfile regelt alles
    startCommand: ""       # leeg, want CMD in Dockerfile bepaalt het
